test

diff --git a/.github/actions/get-all-in-one-list-from-versions-file/action.yml b/.github/actions/get-all-in-one-list-from-versions-file/action.yml
--- a/.github/actions/get-all-in-one-list-from-versions-file/action.yml
+++ b/.github/actions/get-all-in-one-list-from-versions-file/action.yml
@@ -49,27 +49,35 @@ runs:
 
         cd ${WORKING_DIRECTORY}
 
+        if [[ ${VERSION_GROUP} == "all" ]]; then
+          VERSION_GROUP_FILTER=""
+        else
+          VERSION_GROUP_FILTER="\"${VERSION_GROUP}\""
+        fi
+        if [[ "${VERSION_FILTER}" == "all" ]]; then
+          JQ_FILTER="[.[${VERSION_GROUP_FILTER}] | map(.)] | add"
+        elif [[ "${VERSION_FILTER}" == "gettext" ]]; then
+          JQ_FILTER="[.[${VERSION_GROUP_FILTER}] | map(select(.VERSION_COMPENDIUM != \"\") | .)] | add"
+        elif [[ "${VERSION_FILTER}" == "tmscli" ]]; then
+          JQ_FILTER="[.[${VERSION_GROUP_FILTER}] | map(select(.VERSION_COMPENDIUM == \"\") | .)] | add"
+        else
+          echo "Error: Invalid VERSION_FILTER value. (${VERSION_FILTER})" >&2
+          exit 1
+        fi
+        JQ_FILE="${VERSIONS_FILE}"
+        OBJECT_LIST=$(jq -c "${JQ_FILTER}" "${JQ_FILE}")
+
         if [[ "${TYPE}" == "matrix" ]]; then
-          if [[ ${VERSION_GROUP} == "all" ]]; then
-            VERSION_GROUP_FILTER=""
-          else
-            VERSION_GROUP_FILTER="\"${VERSION_GROUP}\""
-          fi
-
-          JQ_FILTER="[.[${VERSION_GROUP_FILTER}] | map(.LANGUAGE_ALL_IN_ONE)] | add"
-          JQ_FILE="${VERSIONS_FILE}"
-          ALL_IN_ONE_LIST=$(jq -c "${JQ_FILTER}" "${JQ_FILE}")
-
+          ALL_IN_ONE_LIST=$(echo "${OBJECT_LIST}" | jq -c "[.[].ALL_IN_ONE]")
         elif [[ "${TYPE}" == "single" ]]; then
-          JQ_FILTER=".[] | .[] | select(.VERSION == \"${VERSION}\") | .LANGUAGE_ALL_IN_ONE"
-          JQ_FILE="${VERSIONS_FILE}"
-          ALL_IN_ONE_VALUE=$(jq -r "${JQ_FILTER}" "${JQ_FILE}")
-
-          if [[ -z "${ALL_IN_ONE_VALUE}" ]]; then
-            echo "Error: No matching entry for version '${VERSION}' in the list." >&2
+          ALL_IN_ONE=$(echo "${OBJECT_LIST}" | jq -r ".[] | select(.VERSION == \"${VERSION}\") | .ALL_IN_ONE")
+          if [ "${ALL_IN_ONE}" == "true" ] || [ "${ALL_IN_ONE}" == "false" ]; then
+            echo "ALL_IN_ONE value for VERSION '${VERSION}' is: ${ALL_IN_ONE}"
+          else
+            echo "Error: Version '${VERSION}' is NOT found in the list." >&2
             exit 1
           fi
-          ALL_IN_ONE_LIST="[ ${ALL_IN_ONE_VALUE} ]"
+          ALL_IN_ONE_LIST="[ \"${ALL_IN_ONE_VALUE}\" ]"
         else
           echo "Error: Invalid TYPE value. (${TYPE})" >&2
           exit 1
